package com.agrogarden

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.net.Uri
import android.os.Build
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.work.Data
import androidx.work.ExistingWorkPolicy
import androidx.work.OneTimeWorkRequestBuilder
import androidx.work.WorkManager
import com.agrogarden.data.*
import com.agrogarden.notifications.ReminderWorker
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.time.Duration
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.concurrent.TimeUnit

class ProductionMainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (Build.VERSION.SDK_INT >= 33) requestPermissions(arrayOf("android.permission.POST_NOTIFICATIONS"), 10)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel("agro", "AgroGarden", NotificationManager.IMPORTANCE_DEFAULT))
        setContent { ProductionApp(AppDb.get(this)) }
    }
}

private data class PPlant(val id:String,val name:String,val category:String,val family:String,val light:String,val water:String,val soil:String,val diseases:String,val pests:String)
private val catalog = listOf(
    PPlant("bean","Фасоль","Овощные","Бобовые","Солнце","Умеренный","Лёгкая плодородная","Антракноз, бактериоз","Тля, фасолевая зерновка"),
    PPlant("tomato","Томат","Овощные","Паслёновые","Солнце","Умеренный","Плодородная","Фитофтороз, кладоспориоз","Белокрылка, тля"),
    PPlant("cucumber","Огурец","Овощные","Тыквенные","Солнце/полутень","Частый","Влажная плодородная","Мучнистая роса","Паутинный клещ, тля"),
    PPlant("apple","Яблоня","Плодово-ягодные","Розовые","Солнце","Умеренный","Суглинистая","Парша, плодовая гниль","Яблонная плодожорка, тля"),
    PPlant("strawberry","Клубника","Плодово-ягодные","Розовые","Солнце","Умеренный","Слабокислая","Серая гниль","Земляничный клещ, долгоносик"),
    PPlant("rose","Роза","Садовые","Розовые","Солнце","Умеренный","Плодородная","Чёрная пятнистость, мучнистая роса","Тля, паутинный клещ"),
    PPlant("ficus","Фикус","Комнатные","Тутовые","Яркий рассеянный","После подсыхания","Воздухопроницаемая","Корневая гниль","Щитовка, мучнистый червец")
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ProductionApp(db:AppDb) {
    val context=LocalContext.current; val scope=rememberCoroutineScope(); var screen by remember{mutableStateOf("home")}; var drawer by remember{mutableStateOf(false)}; var fileMode by remember{mutableStateOf("")}; val drawerState=rememberDrawerState(DrawerValue.Closed)
    LaunchedEffect(drawer){if(drawer)drawerState.open() else drawerState.close()}
    val exportLauncher=rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("application/json")){uri->if(uri!=null)scope.launch{if(fileMode=="backup")exportBackup(context,db,uri)else exportQuiz(context,uri)};fileMode=""}
    val restoreLauncher=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->if(uri!=null)scope.launch{restoreBackup(context,db,uri)}}
    fun nav(s:String){screen=s;drawer=false}
    ModalNavigationDrawer(drawerState=drawerState,drawerContent={ModalDrawerSheet{Text("🌿 AgroGarden",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.padding(20.dp));Item("⌂","Главная",screen=="home"){nav("home")};HorizontalDivider();Text("🌱 Энциклопедия",modifier=Modifier.padding(16.dp));Item("🌿","Растения",screen=="plants"){nav("plants")};Item("♧","Семейства",screen=="families"){nav("families")};Item("🦠","Болезни",screen=="diseases"){nav("diseases")};Item("🐞","Вредители",screen=="pests"){nav("pests")};HorizontalDivider();Text("🚜 Хозяйство",modifier=Modifier.padding(16.dp));listOf("crops" to "🌾 Посевы","seeds" to "🌱 Семена","fertilizers" to "🧪 Удобрения","irrigation" to "💧 Полив","tasks" to "🔔 Напоминания","sales" to "💰 Продажи","harvest" to "🧺 Урожай","expenses" to "📉 Расходы","treatments" to "🛡️ Обработки","calendar" to "📅 Календарь","warehouse" to "📦 Склад","profit" to "📊 Прибыль","notes" to "📝 Блокнот","favorites" to "❤️ Избранное").forEach{(id,label)->Item("",label,screen==id){nav(id)}};HorizontalDivider();Text("💾 Данные",modifier=Modifier.padding(16.dp));Item("","Экспорт / резервная копия",false){fileMode="backup";exportLauncher.launch("agrogarden-backup.json")};Item("","Восстановить из копии",false){restoreLauncher.launch(arrayOf("application/json","text/*"))};Item("","Викторина",false){fileMode="quiz";exportLauncher.launch("agrogarden-quiz.json")}}}){Scaffold(topBar={TopAppBar(title={Text(title(screen))},navigationIcon={IconButton({drawer=true}){Text("☰")}})}){p->Box(Modifier.fillMaxSize().padding(p)){when(screen){"home"->Home(db,::nav);"plants"->Plants(db,"Все растения");"families"->Families();"diseases"->Knowledge("Болезни",catalog.flatMap{p->p.diseases.split(", ").map{it to p.name}}.distinct());"pests"->Knowledge("Вредители",catalog.flatMap{p->p.pests.split(", ").map{it to p.name}}.distinct());"crops"->Crops(db);"seeds"->Seeds(db);"fertilizers"->Fertilizers(db);"irrigation"->Irrigation(db);"tasks"->Tasks(db);"sales"->Sales(db);"harvest"->Harvest(db);"expenses"->Expenses(db);"treatments"->Treatments(db);"calendar"->Calendar(db);"warehouse"->Warehouse(db);"profit"->Profit(db);"notes"->Notes(db);"favorites"->Favorites(db)}}}}}
}
@Composable private fun Item(icon:String,label:String,selected:Boolean,onClick:()->Unit)=NavigationDrawerItem(label={Text(label)},selected=selected,onClick=onClick,icon={if(icon.isNotBlank())Text(icon)},modifier=Modifier.padding(NavigationDrawerItemDefaults.ItemPadding))
private fun title(s:String)=mapOf("home" to "AgroGarden","plants" to "Растения","families" to "Семейства","diseases" to "Болезни","pests" to "Вредители","crops" to "Посевы","seeds" to "Семена","fertilizers" to "Удобрения","irrigation" to "Полив","tasks" to "Напоминания","sales" to "Продажи","harvest" to "Урожай","expenses" to "Расходы","treatments" to "Обработки","calendar" to "Календарь","warehouse" to "Склад","profit" to "Прибыль","notes" to "Блокнот","favorites" to "Избранное")[s]?:"AgroGarden"

@Composable private fun Home(db:AppDb,nav:(String)->Unit){val f by db.fertilizers().all().collectAsState(emptyList());val s by db.seeds().all().collectAsState(emptyList());val t by db.tasks().all().collectAsState(emptyList());val sales by db.sales().all().collectAsState(emptyList());val ex by db.expenses().all().collectAsState(emptyList());val revenue=sales.sumOf{it.quantity*it.price};val costs=ex.sumOf{it.amount};LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Полноценная панель хозяйства",style=MaterialTheme.typography.headlineSmall)};item{Info("⚠️ Минимальные остатки",if(f.any{it.quantity<=it.minStock})"Есть позиции ниже минимума" else "Все остатки в норме")};item{Info("🔔 Напоминания",t.count{!it.done}.toString())};item{Info("📊 Финансы","Выручка ${money(revenue)} • Расходы ${money(costs)} • Прибыль ${money(revenue-costs)}")};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){Button({nav("seeds")},Modifier.weight(1f)){Text("🌱 Семена")};Button({nav("fertilizers")},Modifier.weight(1f)){Text("🧪 Удобрения")}}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){Button({nav("irrigation")},Modifier.weight(1f)){Text("💧 Полив")};Button({nav("tasks")},Modifier.weight(1f)){Text("🔔 Задачи")}}};item{Text("В складе семян: ${s.size} поз.")}}}
@Composable private fun Info(a:String,b:String)=Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(a,style=MaterialTheme.typography.titleMedium);Text(b)}}

@Composable private fun Plants(db:AppDb,filter:String){var q by remember{mutableStateOf("")};var selected by remember{mutableStateOf<PPlant?>(null)};if(selected!=null){LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{TextButton({selected=null}){Text("← Назад")};Text(selected!!.name,style=MaterialTheme.typography.headlineLarge)};item{Info("Категория",selected!!.category)};item{Info("Семейство",selected!!.family)};item{Info("Освещение",selected!!.light)};item{Info("Полив",selected!!.water)};item{Info("Почва",selected!!.soil)};item{Info("Болезни",selected!!.diseases)};item{Info("Вредители",selected!!.pests)}};return};val list=catalog.filter{(filter=="Все растения"||it.category==filter)&&(q.isBlank()||it.name.contains(q,true)||it.family.contains(q,true))};LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),label={Text("Поиск")})};items(list){p->Card{ListItem(headlineContent={Text("🌿 ${p.name}")},supportingContent={Text("${p.category} • ${p.family}")},trailingContent={TextButton({selected=p}){Text("Открыть")}})}}}}
@Composable private fun Families(){val g=catalog.groupBy{it.family};LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(g.entries.toList()){(k,v)->Info(k,v.joinToString{it.name})}}}
@Composable private fun Knowledge(title:String,rows:List<Pair<String,String>>){LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text(title,style=MaterialTheme.typography.headlineSmall)};items(rows){(a,b)->ListItem(headlineContent={Text(a)},supportingContent={Text("Растение: $b")})}}}

@Composable private fun Crops(db:AppDb){val l by db.crops().all().collectAsState(emptyList());val s=rememberCoroutineScope();var n by remember{mutableStateOf("")};var area by remember{mutableStateOf("0")};var sow by remember{mutableStateOf("")};var harv by remember{mutableStateOf("")};Form("Посевы",{Field(n,{n=it},"Культура");Row{Field(area,{area=it},"Площадь",Modifier.weight(1f));Field(sow,{sow=it},"Дата посева",Modifier.weight(1f));Field(harv,{harv=it},"Дата уборки",Modifier.weight(1f))};Add{if(n.isNotBlank())s.launch{db.crops().add(Crop(name=n,area=area.toDoubleOrNull()?:0.0,sowDate=sow,harvestDate=harv,status="Запланировано",notes=""));n=""}}},l,{Text("${it.name} • ${it.area} га • ${it.status}")}){s.launch{db.crops().delete(it)}}}
@Composable private fun Seeds(db:AppDb){val l by db.seeds().all().collectAsState(emptyList());val s=rememberCoroutineScope();var n by remember{mutableStateOf("")};var q by remember{mutableStateOf("0")};var u by remember{mutableStateOf("шт")};var b by remember{mutableStateOf("")};var e by remember{mutableStateOf("")};Form("Семена",{Field(n,{n=it},"Название");Row{Field(q,{q=it},"Количество",Modifier.weight(1f));Field(u,{u=it},"Единица",Modifier.weight(1f))};Row{Field(b,{b=it},"Партия",Modifier.weight(1f));Field(e,{e=it},"Срок годности",Modifier.weight(1f))};Add{if(n.isNotBlank())s.launch{db.seeds().add(Seed(name=n,quantity=q.toDoubleOrNull()?:0.0,unit=u,batch=b,expiry=e));n=""}}},l,{Text("${it.quantity} ${it.unit} • партия ${it.batch} • до ${it.expiry}")}){s.launch{db.seeds().delete(it)}}}
@Composable private fun Fertilizers(db:AppDb){val l by db.fertilizers().all().collectAsState(emptyList());val s=rememberCoroutineScope();var n by remember{mutableStateOf("")};var q by remember{mutableStateOf("0")};var min by remember{mutableStateOf("1")};var u by remember{mutableStateOf("кг")};Form("Удобрения",{Field(n,{n=it},"Название");Row{Field(q,{q=it},"Остаток",Modifier.weight(1f));Field(min,{min=it},"Минимум",Modifier.weight(1f));Field(u,{u=it},"Единица",Modifier.weight(1f))};Add{if(n.isNotBlank())s.launch{db.fertilizers().add(Fertilizer(name=n,quantity=q.toDoubleOrNull()?:0.0,unit=u,minStock=min.toDoubleOrNull()?:0.0));n=""}}},l,{Text(if(it.quantity<=it.minStock)"⚠️ НИЖЕ МИНИМУМА: ${it.quantity} ${it.unit} / ${it.minStock}" else "✅ ${it.quantity} ${it.unit} / минимум ${it.minStock}")}){s.launch{db.fertilizers().delete(it)}}}

@Composable private fun Irrigation(db:AppDb){val l by db.irrigations().all().collectAsState(emptyList());val s=rememberCoroutineScope();val c=LocalContext.current;var crop by remember{mutableStateOf("")};var d by remember{mutableStateOf("")};var t by remember{mutableStateOf("")};var v by remember{mutableStateOf("0")};var r by remember{mutableStateOf("7")};Form("Полив",{Field(crop,{crop=it},"Культура");Row{Field(d,{d=it},"Дата YYYY-MM-DD",Modifier.weight(1f));Field(t,{t=it},"Время HH:mm",Modifier.weight(1f))};Row{Field(v,{v=it},"Объём",Modifier.weight(1f));Field(r,{r=it},"Каждые N дней",Modifier.weight(1f))};Add{if(crop.isNotBlank())s.launch{val x=Irrigation(crop=crop,date=d,time=t,volume=v.toDoubleOrNull()?:0.0,repeatDays=r.toIntOrNull()?.coerceAtLeast(1)?:7);db.irrigations().add(x);schedule(c,"Полив: ${x.crop}",x.date,x.time,x.repeatDays,key("i",x.crop,x.date,x.time));crop=""}}},l,{Text("${it.date} ${it.time} • ${it.crop} • ${it.volume} • каждые ${it.repeatDays} дн.")}){s.launch{db.irrigations().delete(it);cancel(c,key("i",it.crop,it.date,it.time))}}}
@Composable private fun Tasks(db:AppDb){val l by db.tasks().all().collectAsState(emptyList());val s=rememberCoroutineScope();val c=LocalContext.current;var n by remember{mutableStateOf("")};var d by remember{mutableStateOf("")};var t by remember{mutableStateOf("")};var r by remember{mutableStateOf("1")};Form("Напоминания",{Field(n,{n=it},"Задача");Row{Field(d,{d=it},"Дата YYYY-MM-DD",Modifier.weight(1f));Field(t,{t=it},"Время HH:mm",Modifier.weight(1f))};Field(r,{r=it},"Повтор каждые N дней");Add{if(n.isNotBlank())s.launch{val x=Task(title=n,date=d,time=t,repeatDays=r.toIntOrNull()?.coerceAtLeast(1)?:1);db.tasks().add(x);schedule(c,x.title,x.date,x.time,x.repeatDays,key("t",x.title,x.date,x.time));n=""}}},l,{Text("🔔 ${it.date} ${it.time} • ${it.title} • каждые ${it.repeatDays} дн.")}){s.launch{db.tasks().delete(it);cancel(c,key("t",it.title,it.date,it.time))}}}
@Composable private fun Sales(db:AppDb){val l by db.sales().all().collectAsState(emptyList());val s=rememberCoroutineScope();var p by remember{mutableStateOf("")};var q by remember{mutableStateOf("0")};var pr by remember{mutableStateOf("0")};var b by remember{mutableStateOf("")};var d by remember{mutableStateOf("")};Form("Продажи",{Field(p,{p=it},"Товар");Row{Field(q,{q=it},"Количество",Modifier.weight(1f));Field(pr,{pr=it},"Цена",Modifier.weight(1f))};Row{Field(b,{b=it},"Покупатель",Modifier.weight(1f));Field(d,{d=it},"Дата",Modifier.weight(1f))};Add{if(p.isNotBlank())s.launch{db.sales().add(Sale(product=p,quantity=q.toDoubleOrNull()?:0.0,price=pr.toDoubleOrNull()?:0.0,buyer=b,date=d));p=""}}},l,{Text("${it.product}: ${it.quantity} × ${it.price} = ${money(it.quantity*it.price)} • ${it.buyer}")}){s.launch{db.sales().delete(it)}}}
@Composable private fun Harvest(db:AppDb){val l by db.harvests().all().collectAsState(emptyList());val s=rememberCoroutineScope();var c by remember{mutableStateOf("")};var q by remember{mutableStateOf("0")};var d by remember{mutableStateOf("")};var qual by remember{mutableStateOf("")};Form("Урожай",{Field(c,{c=it},"Культура");Row{Field(q,{q=it},"Количество",Modifier.weight(1f));Field(d,{d=it},"Дата",Modifier.weight(1f));Field(qual,{qual=it},"Качество",Modifier.weight(1f))};Add{if(c.isNotBlank())s.launch{db.harvests().add(Harvest(crop=c,quantity=q.toDoubleOrNull()?:0.0,date=d,quality=qual));c=""}}},l,{Text("${it.crop} • ${it.quantity} • ${it.date} • ${it.quality}")}){s.launch{db.harvests().delete(it)}}}
@Composable private fun Expenses(db:AppDb){val l by db.expenses().all().collectAsState(emptyList());val s=rememberCoroutineScope();var c by remember{mutableStateOf("")};var a by remember{mutableStateOf("0")};var d by remember{mutableStateOf("")};var n by remember{mutableStateOf("")};Form("Расходы",{Field(c,{c=it},"Материал / категория");Row{Field(a,{a=it},"Сумма",Modifier.weight(1f));Field(d,{d=it},"Дата",Modifier.weight(1f))};Field(n,{n=it},"Комментарий");Add{if(c.isNotBlank())s.launch{db.expenses().add(Expense(category=c,amount=a.toDoubleOrNull()?:0.0,date=d,note=n));c=""}}},l,{Text("${it.category}: ${money(it.amount)} • ${it.date} • ${it.note}")}){s.launch{db.expenses().delete(it)}}}
@Composable private fun Treatments(db:AppDb){val l by db.treatments().all().collectAsState(emptyList());val s=rememberCoroutineScope();var c by remember{mutableStateOf("")};var i by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};var d by remember{mutableStateOf("")};var n by remember{mutableStateOf("")};Form("Обработки",{Field(c,{c=it},"Культура");Row{Field(i,{i=it},"Болезнь / вредитель / профилактика",Modifier.weight(1f));Field(p,{p=it},"Препарат",Modifier.weight(1f))};Row{Field(d,{d=it},"Дата",Modifier.weight(1f));Field(n,{n=it},"Примечание",Modifier.weight(1f))};Add{if(c.isNotBlank())s.launch{db.treatments().add(Treatment(crop=c,issue=i,product=p,date=d,note=n));c=""}}},l,{Text("${it.crop} • ${it.issue} • ${it.product} • ${it.date}")}){s.launch{db.treatments().delete(it)}}}
@Composable private fun Notes(db:AppDb){val l by db.notes().all().collectAsState(emptyList());val s=rememberCoroutineScope();var t by remember{mutableStateOf("")};var x by remember{mutableStateOf("")};Form("Блокнот",{Field(t,{t=it},"Заголовок");Field(x,{x=it},"Запись");Add{if(x.isNotBlank())s.launch{db.notes().add(Note(title=t.ifBlank{"Заметка"},text=x));t="";x=""}}},l,{Text("${it.title}: ${it.text}")}){s.launch{db.notes().delete(it)}}}

@Composable private fun Calendar(db:AppDb){val i by db.irrigations().all().collectAsState(emptyList());val t by db.tasks().all().collectAsState(emptyList());LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){item{Text("Поливы и аграрные задачи",style=MaterialTheme.typography.headlineSmall)};items(i){ListItem(headlineContent={Text("💧 ${it.date} ${it.time}")},supportingContent={Text("${it.crop} • ${it.volume} • повтор ${it.repeatDays} дн.")})};items(t){ListItem(headlineContent={Text("🔔 ${it.date} ${it.time}")},supportingContent={Text("${it.title} • повтор ${it.repeatDays} дн.")})}}}
@Composable private fun Warehouse(db:AppDb){val s by db.seeds().all().collectAsState(emptyList());val f by db.fertilizers().all().collectAsState(emptyList());LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){item{Text("Семена",style=MaterialTheme.typography.titleLarge)};items(s){ListItem(headlineContent={Text(it.name)},supportingContent={Text("${it.quantity} ${it.unit} • партия ${it.batch} • годность ${it.expiry}")})};item{Text("Удобрения",style=MaterialTheme.typography.titleLarge)};items(f){ListItem(headlineContent={Text(it.name)},supportingContent={Text("${it.quantity} ${it.unit} • минимум ${it.minStock} ${if(it.quantity<=it.minStock)"⚠️" else "✅"}")})}}}
@Composable private fun Profit(db:AppDb){val s by db.sales().all().collectAsState(emptyList());val e by db.expenses().all().collectAsState(emptyList());val r=s.sumOf{it.quantity*it.price};val c=e.sumOf{it.amount};LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Info("💰 Выручка",money(r))};item{Info("📉 Расходы",money(c))};item{Info("📊 Прибыль",money(r-c))};item{Text("Продажи",style=MaterialTheme.typography.titleLarge)};items(s){Text("${it.product}: ${money(it.quantity*it.price)}")};item{Text("Расходы",style=MaterialTheme.typography.titleLarge)};items(e){Text("${it.category}: ${money(it.amount)}")}}}
@Composable private fun Favorites(db:AppDb){val f by db.favorites().all().collectAsState(emptyList());val p=f.mapNotNull{x->catalog.find{it.id==x.plantId}};LazyColumn(Modifier.padding(12.dp)){if(p.isEmpty())item{Text("Избранных растений пока нет.")};items(p){Info(it.name,"${it.category} • ${it.family}")}}}

@Composable private fun <T> Form(title:String,form:@Composable ColumnScope.() -> Unit,list:List<T>,summary: @Composable (T) -> Unit,delete:(T)->Unit){LazyColumn(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text(title,style=MaterialTheme.typography.headlineSmall);Column(verticalArrangement=Arrangement.spacedBy(8.dp),content=form)};items(list){x->Card{Row(Modifier.fillMaxWidth().padding(8.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){Box(Modifier.weight(1f)){summary(x)};TextButton({delete(x)}){Text("🗑️")}}}}}}
@Composable private fun Field(v:String,set:(String)->Unit,label:String,modifier:Modifier=Modifier.fillMaxWidth())=OutlinedTextField(v,set,modifier,label={Text(label)})
@Composable private fun Add(onClick:()->Unit)=Button(onClick,Modifier.fillMaxWidth()){Text("➕ Добавить")}

private val fmt=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")
private fun key(prefix:String,vararg values:String)=(prefix+"_"+values.joinToString("|")).hashCode().toString()
private fun schedule(context:Context,title:String,date:String,time:String,repeat:Int,name:String){try{val target=LocalDateTime.parse("$date $time",fmt);val delay=Duration.between(LocalDateTime.now(),target).toMillis().coerceAtLeast(0);val data=Data.Builder().putString("title",title).putInt("repeatDays",repeat).putString("dateTime",target.toString()).putString("uniqueName",name).build();val req=OneTimeWorkRequestBuilder<ReminderWorker>().setInitialDelay(delay,TimeUnit.MILLISECONDS).setInputData(data).build();WorkManager.getInstance(context).enqueueUniqueWork(name,ExistingWorkPolicy.REPLACE,req)}catch(_:Exception){}}
private fun cancel(context:Context,name:String)=WorkManager.getInstance(context).cancelUniqueWork(name)
private fun money(v:Double)="%.2f".format(java.util.Locale.US,v)

private suspend fun exportBackup(context:Context,db:AppDb,uri:Uri)=withContext(Dispatchers.IO){val root=JSONObject().put("version",3).put("createdAt",System.currentTimeMillis());fun<T> arr(list:List<T>,map:(T)->JSONObject)=JSONArray().also{a->list.forEach{a.put(map(it))}};root.put("crops",arr(db.crops().all().first()){JSONObject().put("id",it.id).put("name",it.name).put("area",it.area).put("sowDate",it.sowDate).put("harvestDate",it.harvestDate).put("status",it.status).put("notes",it.notes)});root.put("seeds",arr(db.seeds().all().first()){JSONObject().put("id",it.id).put("name",it.name).put("quantity",it.quantity).put("unit",it.unit).put("batch",it.batch).put("expiry",it.expiry)});root.put("fertilizers",arr(db.fertilizers().all().first()){JSONObject().put("id",it.id).put("name",it.name).put("quantity",it.quantity).put("unit",it.unit).put("minStock",it.minStock)});root.put("irrigations",arr(db.irrigations().all().first()){JSONObject().put("id",it.id).put("crop",it.crop).put("date",it.date).put("time",it.time).put("volume",it.volume).put("repeatDays",it.repeatDays)});root.put("sales",arr(db.sales().all().first()){JSONObject().put("id",it.id).put("product",it.product).put("quantity",it.quantity).put("price",it.price).put("buyer",it.buyer).put("date",it.date)});root.put("harvests",arr(db.harvests().all().first()){JSONObject().put("id",it.id).put("crop",it.crop).put("quantity",it.quantity).put("date",it.date).put("quality",it.quality)});root.put("expenses",arr(db.expenses().all().first()){JSONObject().put("id",it.id).put("category",it.category).put("amount",it.amount).put("date",it.date).put("note",it.note)});root.put("treatments",arr(db.treatments().all().first()){JSONObject().put("id",it.id).put("crop",it.crop).put("issue",it.issue).put("product",it.product).put("date",it.date).put("note",it.note)});root.put("tasks",arr(db.tasks().all().first()){JSONObject().put("id",it.id).put("title",it.title).put("date",it.date).put("time",it.time).put("repeatDays",it.repeatDays).put("done",it.done)});root.put("notes",arr(db.notes().all().first()){JSONObject().put("id",it.id).put("title",it.title).put("text",it.text).put("createdAt",it.createdAt)});root.put("favorites",arr(db.favorites().all().first()){JSONObject().put("plantId",it.plantId).put("addedAt",it.addedAt)});context.contentResolver.openOutputStream(uri)?.use{it.write(root.toString(2).toByteArray(Charsets.UTF_8))}}
private suspend fun restoreBackup(context:Context,db:AppDb,uri:Uri)=withContext(Dispatchers.IO){val text=context.contentResolver.openInputStream(uri)?.bufferedReader()?.use{it.readText()}?:return@withContext;val root=JSONObject(text);db.clearAllTables();fun arr(n:String)=root.optJSONArray(n)?:JSONArray();var a=arr("crops");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.crops().add(Crop(x.optLong("id"),x.optString("name"),x.optDouble("area"),x.optString("sowDate"),x.optString("harvestDate"),x.optString("status"),x.optString("notes")))};a=arr("seeds");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.seeds().add(Seed(x.optLong("id"),x.optString("name"),x.optDouble("quantity"),x.optString("unit"),x.optString("batch"),x.optString("expiry")))};a=arr("fertilizers");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.fertilizers().add(Fertilizer(x.optLong("id"),x.optString("name"),x.optDouble("quantity"),x.optString("unit"),x.optDouble("minStock")))};a=arr("irrigations");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.irrigations().add(Irrigation(x.optLong("id"),x.optString("crop"),x.optString("date"),x.optString("time"),x.optDouble("volume"),x.optInt("repeatDays",1)))};a=arr("sales");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.sales().add(Sale(x.optLong("id"),x.optString("product"),x.optDouble("quantity"),x.optDouble("price"),x.optString("buyer"),x.optString("date")))};a=arr("harvests");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.harvests().add(Harvest(x.optLong("id"),x.optString("crop"),x.optDouble("quantity"),x.optString("date"),x.optString("quality")))};a=arr("expenses");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.expenses().add(Expense(x.optLong("id"),x.optString("category"),x.optDouble("amount"),x.optString("date"),x.optString("note")))};a=arr("treatments");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.treatments().add(Treatment(x.optLong("id"),x.optString("crop"),x.optString("issue"),x.optString("product"),x.optString("date"),x.optString("note")))};a=arr("tasks");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.tasks().add(Task(x.optLong("id"),x.optString("title"),x.optString("date"),x.optString("time"),x.optInt("repeatDays",1),x.optBoolean("done")))};a=arr("notes");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.notes().add(Note(x.optLong("id"),x.optString("title"),x.optString("text"),x.optLong("createdAt")))};a=arr("favorites");for(i in 0 until a.length()){val x=a.getJSONObject(i);db.favorites().add(FavoritePlant(x.optString("plantId"),x.optLong("addedAt")))}}
private fun exportQuiz(context:Context,uri:Uri){context.contentResolver.openOutputStream(uri)?.use{it.write("AgroGarden — викторина\n\n1. Что показывает minStock?\nA) Минимальный остаток удобрения\nB) Период полива\n\n2. Для чего нужен WorkManager?\nA) Для фоновых задач и напоминаний\nB) Для хранения фото\n".toByteArray(Charsets.UTF_8))}
